
#pragma kernel March

#include "Includes/MarchingTable.hlsl"
#include "Includes/Helper.hlsl"




float _IsoLevel;
uint _ChunkSize;
int _VoxekWidth;
int _VoxelHeight;
uint _voxelSize;
float3 voxelpos;

struct Triangle
{
    float3 a, b, c;
    float4 col_a, col_b, col_c;
};


struct VoxelData_v2
{
       
    float DistanceToSurface;
    uint TexIndex;
      
};

RWStructuredBuffer<VoxelData_v2> _Weights;
AppendStructuredBuffer<Triangle> _Triangles;

//initialize helper function
void SetMetricsChunkSize()
{
    _Metrics_VoxelWidth = _VoxekWidth;
    _Metrics_VoxelSize = _voxelSize;
   
}

//return edge sample
float3 EdgeInterpolation(float3 edgeVertex1, float valueAtVertex1, float3 edgeVertex2, float valueAtVertex2)
{
    float3 v1 = edgeVertex1 * _voxelSize;
    float3 v2 = edgeVertex2 * _voxelSize;
    return v1 + (_IsoLevel - valueAtVertex1) * (v2 - v1) / (valueAtVertex2 - valueAtVertex1);
}

//return color based on texture sample
float4 SampleTextureIndex(uint textIndex)
{
    if (textIndex == 0)
    {
        return float4(1, 1, 1, 1);
    }
    else if (textIndex == 1)
    {
        return float4(1, 0, 0, 1);
    }
    else if (textIndex == 2)
    {
        return float4(0, 1, 0, 1);
    }
    else if (textIndex == 3)
    {
        return float4(0, 0, 1, 1);
    }
    
    return float4(0, 0, 0, 1);
}


[numthreads(numThreads, numThreads, numThreads)]
void March(uint3 id : SV_DispatchThreadID)
{
    voxelpos = id * _voxelSize;
   
    //initialize helper function
    if (_Metrics_VoxelSize == 0)
    {
        SetMetricsChunkSize();
    }
    
    
    //return if out of bounds
    if (id.x * _voxelSize >= _ChunkSize || id.y * _voxelSize >= _VoxelHeight - 1 || id.z * _voxelSize >= _ChunkSize)
    {
        return;
    }
    
    
    //set cube values from weights
    float cubeValues[8] =
    {
        _Weights[indexFromCoord(voxelpos.x, voxelpos.y, voxelpos.z + _voxelSize, _VoxelHeight)].DistanceToSurface,
     _Weights[indexFromCoord(voxelpos.x + _voxelSize, voxelpos.y, voxelpos.z + _voxelSize, _VoxelHeight)].DistanceToSurface,
     _Weights[indexFromCoord(voxelpos.x + _voxelSize, voxelpos.y, voxelpos.z, _VoxelHeight)].DistanceToSurface,
     _Weights[indexFromCoord(voxelpos.x, voxelpos.y, voxelpos.z, _VoxelHeight)].DistanceToSurface,
     _Weights[indexFromCoord(voxelpos.x, voxelpos.y + _voxelSize, voxelpos.z + _voxelSize, _VoxelHeight)].DistanceToSurface,
     _Weights[indexFromCoord(voxelpos.x + _voxelSize, voxelpos.y + _voxelSize, voxelpos.z + _voxelSize, _VoxelHeight)].DistanceToSurface,
     _Weights[indexFromCoord(voxelpos.x + _voxelSize, voxelpos.y + _voxelSize, voxelpos.z, _VoxelHeight)].DistanceToSurface,
     _Weights[indexFromCoord(voxelpos.x, voxelpos.y + _voxelSize, voxelpos.z, _VoxelHeight)].DistanceToSurface
    };
    
    //set cubeindex based on bitwise masking
    int cubeIndex = 0;
    if (cubeValues[0] < _IsoLevel)
        cubeIndex |= 1;
    if (cubeValues[1] < _IsoLevel)
        cubeIndex |= 2;
    if (cubeValues[2] < _IsoLevel)
        cubeIndex |= 4;
    if (cubeValues[3] < _IsoLevel)
        cubeIndex |= 8;
    if (cubeValues[4] < _IsoLevel)
        cubeIndex |= 16;
    if (cubeValues[5] < _IsoLevel)
        cubeIndex |= 32;
    if (cubeValues[6] < _IsoLevel)
        cubeIndex |= 64;
    if (cubeValues[7] < _IsoLevel)
        cubeIndex |= 128;
    
    
    //get triangle edges from triangletable
    int edges[] = triTable[cubeIndex];
    
    //voxelpos = id;
    
    //loop through the edges
    for (int i = 0; edges[i] != -1; i += 3)
    {
        int edge00 = edgeConnections[edges[i]][0];
        int edge01 = edgeConnections[edges[i]][1];
        
        int edge10 = edgeConnections[edges[i + 1]][0];
        int edge11 = edgeConnections[edges[i + 1]][1];
        
        int edge20 = edgeConnections[edges[i + 2]][0];
        int edge21 = edgeConnections[edges[i + 2]][1];
        
        Triangle tri;
       
      
        tri.a = (EdgeInterpolation(cornerOffsets[edge00], cubeValues[edge00], cornerOffsets[edge01], cubeValues[edge01]) + voxelpos) * _voxelSize;
        tri.b =( EdgeInterpolation(cornerOffsets[edge10], cubeValues[edge10], cornerOffsets[edge11], cubeValues[edge11]) + voxelpos) * _voxelSize;
        tri.c = (EdgeInterpolation(cornerOffsets[edge20], cubeValues[edge20], cornerOffsets[edge21], cubeValues[edge21]) + voxelpos) * _voxelSize;
        
       
        
        tri.col_a = SampleTextureIndex(_Weights[indexFromCoord(tri.a.x / _voxelSize, tri.a.y / _voxelSize, tri.a.z / _voxelSize, _VoxelHeight)].TexIndex);
        tri.col_b = SampleTextureIndex(_Weights[indexFromCoord(tri.b.x / _voxelSize, tri.b.y / _voxelSize, tri.b.z / _voxelSize, _VoxelHeight)].TexIndex);
        tri.col_c = SampleTextureIndex(_Weights[indexFromCoord(tri.c.x / _voxelSize, tri.c.y / _voxelSize, tri.c.z / _voxelSize, _VoxelHeight)].TexIndex);
        
        
    
    
        
        _Triangles.Append(tri);
    }

}
